Repository smartcontractkit/documentation, pull requests merged in 2022-07, with the labels that each got.

#837 improve EthBalanceMonitor formatting
  docs/chainlink-keepers/util-overview.md
  docs/chainlink-keepers/utility-contracts.md
Labels: evm, keepers

#824 Add a cron to maintain chains.json
  .github/workflows/chains-metadata.yml
  .gitignore
  _src/chains-metadata.ts
  package.json
  yarn.lock
Labels: enhancement, ready to merge

#835 improve terminology in keepers best practices
  docs/chainlink-keepers/compatible-contracts.md
Labels: evm, keepers

#855 Update typeform URLs
  docs/Developer Reference/selecting-data-feeds.md
Labels: ready to merge

#857 Correct mode task docs
  docs/Oracle Jobs/Task Types/task_mode.md
Labels: ready to merge, node operators

#861 v1.6.0 release notes
  docs/Node Operators/node-versions.md
Labels: node operators

#865 Add Discord URL to the data-feeds-user-notifications channel
  docs/Developer Reference/selecting-data-feeds.md
Labels: ready to merge

#863 Update the Forex note to clarify some currencies use unique windows
  _includes/feed.liquid
Labels: blocked

#867 Add Keepers examples
  docs/chainlink-keepers/util-overview.md
  docs/chainlink-keepers/utility-contracts.md
Labels: keepers

#866 Add 'Job Scheduler' Note to cron page
  docs/Oracle Jobs/Job Types/cron.md
Labels: ready to merge, node operators, keepers

#864 Kovan deprecation, replace RPCs, add code notices
  _includes/samples/APIRequests/APIConsumer.sol
  _includes/samples/APIRequests/ATestnetConsumer.sol
  _includes/samples/APIRequests/FetchFromArray.sol
  _includes/samples/APIRequests/GenericBigWord.sol
  _includes/samples/APIRequests/GetGasPrice.sol
  _includes/samples/APIRequests/MultiWordConsumer.sol
  _includes/samples/DataProviders/DnsOwnership.sol
  _includes/samples/DataProviders/Finage.sol
  _includes/samples/DataProviders/GoogleWeather.sol
  _includes/samples/DataProviders/Kraken.sol
  _includes/samples/FeedRegistry/PriceConsumer.js
  _includes/samples/FeedRegistry/PriceConsumer.sol
  _includes/samples/Keepers/BalancerOffChain.sol
  _includes/samples/Keepers/BalancerOnChain.sol
  _includes/samples/Keepers/EthBalanceMonitor.sol
  _includes/samples/Keepers/KeepersCounter.sol
  _includes/samples/Keepers/example.sol
  _includes/samples/NodeOperators/jobs/get-bytes32.toml
  _includes/samples/NodeOperators/jobs/get-string.toml
  _includes/samples/NodeOperators/jobs/get-uint256.toml
  _includes/samples/PriceFeeds/ArbitrumPriceConsumer.sol
  _includes/samples/PriceFeeds/ENSConsumer.js
  _includes/samples/PriceFeeds/ENSConsumer.sol
  _includes/samples/PriceFeeds/HistoricalPriceConsumer.js
  _includes/samples/PriceFeeds/HistoricalPriceConsumer.py
  _includes/samples/PriceFeeds/HistoricalPriceConsumer.sol
  _includes/samples/PriceFeeds/PriceConsumerV3.js
  _includes/samples/PriceFeeds/PriceConsumerV3.py
  _includes/samples/PriceFeeds/PriceConsumerV3Ethers.js
  _includes/samples/PriceFeeds/PriceConverter.sol
  _includes/samples/Solana/PriceFeeds/off-chain-read.js
  _includes/samples/Solana/PriceFeeds/off-chain-read.ts
  _includes/samples/Solana/PriceFeeds/on-chain-read-anchor.rs
  _includes/samples/Solana/PriceFeeds/on-chain-read.rs
  _includes/samples/Tutorials/HelloWorld.sol
  _includes/samples/Tutorials/Test.sol
  _includes/samples/VRF/RandomNumberConsumer.sol
  _includes/samples/VRF/VRFD20.sol
  _includes/samples/VRF/VRFv2Consumer.sol
  _includes/samples/VRF/VRFv2SubscriptionManager.sol
  _includes/samples/events/avasummit/VRFv2SubscriptionManager.sol
  _src/get-latest-price-feed-registry.js
  _src/get-latest-price.js
  _tools/networks.ts
  docs/Using Price Feeds/feed-registry.html
  docs/Using Price Feeds/get-the-latest-price.html
  docs/Using Price Feeds/historical-price-data.html
Labels: ready to merge, data feeds, evm

#872 Package updates and minor fixes
  _src/prism.css
  _src/prism.js
  docs/External Adapters/developers.md
  docs/External Initiators/building-external-initiators.md
  docs/External Initiators/external-initiators-in-nodes.md
  docs/Node Operators/best-practices-aws.md
  docs/Node Operators/configuration-variables.md
  docs/Node Operators/evm-performance-configuration.md
  docs/Node Operators/miscellaneous.md
  docs/Node Operators/run-an-ethereum-client.md
  docs/Oracle Jobs/Task Types/task_jsonparse.md
  package.json
  yarn.lock
Labels: enhancement, ready to merge

#873 Update the Smartcon banner
  _includes/main.liquid
Labels: blocked

#830 Update the L2 sequencer feed examples
  _includes/samples/PriceFeeds/ArbitrumPriceConsumer.sol
  _includes/samples/PriceFeeds/PriceConsumerWithSequencerCheck.sol
  _src/images/data-feed/l2-diagram-arbitrum.svg
  _src/images/data-feed/l2-diagram-arbitrum.webp
  _src/images/data-feed/l2-diagram-optimism-metis.svg
  _src/images/data-feed/l2-diagram-optimism-metis.webp
  _src/images/data-feed/l2-diagram.png
  _src/images/data-feed/seq-down-1.svg
  _src/images/data-feed/seq-down-1.webp
  _src/images/data-feed/seq-down-2.svg
  _src/images/data-feed/seq-down-2.webp
  docs/Contract Creators/l2-sequencer-flag.md
  docs/Using Price Feeds/l2-sequencer-feeds/l2-sequencer-flag.md
Labels: ready to merge, data feeds
