Repository smartcontractkit/documentation, pull requests merged in 2022-03, with the labels that each got.

#552 docs: update ens page
  _src/ens.js
  docs/Using Price Feeds/reference-contracts/ens.html
Labels: ready to merge

#609 [1.2.0] Documentation changes for 1.2.0
  docs/Node Operators/configuration-variables.md
  docs/Node Operators/node-versions.md
  docs/Node Operators/run-an-ethereum-client.md
  docs/Node Operators/running-a-chainlink-node.md
Labels: ready to merge

#617 Comment unused variables to avoid warning messages
  _includes/samples/PriceFeeds/PriceConsumerV3.sol
Labels: ready to merge

#649 Update API key paths for GetBlock connections
  docs/Node Operators/run-an-ethereum-client.md
Labels: ready to merge

#656 Add DappTools and Foundry starter kits
  docs/Developer Reference/create-a-chainlinked-project.md
Labels: ready to merge, evm, framework

#666 Keepers: Add Avalanche Fuji Testnet
  docs/chainlink-keepers/introduction.md
Labels: evm, keepers

#660 Add Avasummit announce page
  _includes/events.liquid
  _includes/samples/events/avasummit/VRFv2SubscriptionManager.sol
  docs/events/avasummit/overview.md
Labels: data feeds, evm, keepers, vrf

#668 Fix keepers ui link
  docs/events/avasummit/overview.md
Labels: data feeds, evm, keepers, vrf

#671 Update the VRF video URL
  docs/Using Randomness/chainlink-vrf.md
Labels: evm, vrf

#669 updated for comma delimited
  _includes/samples/APIRequests/APIConsumer.sol
  _includes/samples/APIRequests/ATestnetConsumer.sol
  docs/Introduction/tutorials/advanced-tutorial.md
  docs/Oracle Jobs/adapters.md
Labels: evm, api call

#678 Add a banner for the April 2022 Hackathon
  _includes/main.liquid
Labels: ready to merge

#676 Add issues templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhance.yml
  .github/ISSUE_TEMPLATE/new_content.yml
Labels: enhancement

#681 Update terra testnet feeds
  docs/Solana/DataFeeds/data-feeds-solana.md
  docs/Terra/DataFeeds/data-feeds-terra.md
  docs/Terra/DataFeeds/using-data-feeds-terra.md
  docs/Using Price Feeds/arbitrum-price-feeds.md
  docs/Using Price Feeds/avalanche-price-feeds.md
  docs/Using Price Feeds/data-feeds-moonriver.md
  docs/Using Price Feeds/fantom-price-feeds.md
  docs/Using Price Feeds/harmony-price-feeds.md
  docs/Using Price Feeds/optimism-price-feeds.md
Labels: ready to merge
